// Mock data for the music app

export const mockSongs = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    artistId: 1,
    album: "After Hours",
    releaseYear: 2020,
    duration: 203,
    genre: "Synth-pop",
    coverArt: "/blinding-lights-album-cover.png",
    audioUrl: "AnhBoVai.mp3",
    lyrics:
      "I've been tryna call\nI've been on my own for long enough\nMaybe you can show me how to love, maybe\nI'm going through withdrawals\nYou don't even have to do too much\nYou can turn me on with just a touch, baby\n\nI look around and Sin City's cold and empty (oh)\nNo one's around to judge me (oh)\nI can't see clearly when you're gone\n\nI said, ooh, I'm blinded by the lights\nNo, I can't sleep until I feel your touch\nI said, ooh, I'm drowning in the night\nOh, when I'm like this, you're the one I trust",
  },
  {
    id: 2,
    title: "Save Your Tears",
    artist: "The Weeknd",
    artistId: 1,
    album: "After Hours",
    releaseYear: 2020,
    duration: 215,
    genre: "Synth-pop",
    coverArt: "/save-your-tears-album-cover.png",
    audioUrl: "",
  },
  {
    id: 3,
    title: "Levitating",
    artist: "Dua Lipa",
    artistId: 2,
    album: "Future Nostalgia",
    releaseYear: 2020,
    duration: 203,
    genre: "Dance-pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+levitating+dua+lipa",
    audioUrl: "",
  },
  {
    id: 4,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    artistId: 3,
    album: "Fine Line",
    releaseYear: 2019,
    duration: 174,
    genre: "Pop rock",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+watermelon+sugar+harry+styles",
    audioUrl: "",
  },
  {
    id: 5,
    title: "Dynamite",
    artist: "BTS",
    artistId: 4,
    album: "BE",
    releaseYear: 2020,
    duration: 199,
    genre: "Disco-pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+dynamite+bts",
    audioUrl: "",
  },
  {
    id: 6,
    title: "drivers license",
    artist: "Olivia Rodrigo",
    artistId: 5,
    album: "SOUR",
    releaseYear: 2021,
    duration: 242,
    genre: "Pop ballad",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+drivers+license+olivia+rodrigo",
    audioUrl: "",
  },
  {
    id: 7,
    title: "good 4 u",
    artist: "Olivia Rodrigo",
    artistId: 5,
    album: "SOUR",
    releaseYear: 2021,
    duration: 178,
    genre: "Pop punk",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+good+4+u+olivia+rodrigo",
    audioUrl: "",
  },
  {
    id: 8,
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    artistId: 6,
    album: "F*CK LOVE 3: OVER YOU",
    releaseYear: 2021,
    duration: 141,
    genre: "Pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+stay+the+kid+laroi",
    audioUrl: "",
  },
  {
    id: 9,
    title: "Montero (Call Me By Your Name)",
    artist: "Lil Nas X",
    artistId: 7,
    album: "MONTERO",
    releaseYear: 2021,
    duration: 137,
    genre: "Pop rap",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+montero+lil+nas+x",
    audioUrl: "",
  },
  {
    id: 10,
    title: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    artistId: 8,
    album: "Planet Her",
    releaseYear: 2021,
    duration: 208,
    genre: "R&B",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+kiss+me+more+doja+cat",
    audioUrl: "",
  },
  {
    id: 11,
    title: "Bad Habits",
    artist: "Ed Sheeran",
    artistId: 9,
    album: "=",
    releaseYear: 2021,
    duration: 230,
    genre: "Synth-pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+bad+habits+ed+sheeran",
    audioUrl: "",
  },
  {
    id: 12,
    title: "Peaches",
    artist: "Justin Bieber ft. Daniel Caesar, Giveon",
    artistId: 10,
    album: "Justice",
    releaseYear: 2021,
    duration: 198,
    genre: "R&B",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+peaches+justin+bieber",
    audioUrl: "",
  },
  {
    id: 13,
    title: "Butter",
    artist: "BTS",
    artistId: 4,
    album: "Butter",
    releaseYear: 2021,
    duration: 164,
    genre: "Dance-pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+butter+bts",
    audioUrl: "",
  },
  {
    id: 14,
    title: "Leave The Door Open",
    artist: "Silk Sonic",
    artistId: 11,
    album: "An Evening with Silk Sonic",
    releaseYear: 2021,
    duration: 242,
    genre: "R&B",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+leave+the+door+open+silk+sonic",
    audioUrl: "",
  },
  {
    id: 15,
    title: "Happier Than Ever",
    artist: "Billie Eilish",
    artistId: 12,
    album: "Happier Than Ever",
    releaseYear: 2021,
    duration: 298,
    genre: "Alternative",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+happier+than+ever+billie+eilish",
    audioUrl: "",
  },
  {
    id: 16,
    title: "Industry Baby",
    artist: "Lil Nas X ft. Jack Harlow",
    artistId: 7,
    album: "MONTERO",
    releaseYear: 2021,
    duration: 212,
    genre: "Hip hop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+industry+baby+lil+nas+x",
    audioUrl: "",
  },
  {
    id: 17,
    title: "Easy On Me",
    artist: "Adele",
    artistId: 13,
    album: "30",
    releaseYear: 2021,
    duration: 224,
    genre: "Pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+easy+on+me+adele",
    audioUrl: "",
  },
  {
    id: 18,
    title: "Heat Waves",
    artist: "Glass Animals",
    artistId: 14,
    album: "Dreamland",
    releaseYear: 2020,
    duration: 238,
    genre: "Indie pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+heat+waves+glass+animals",
    audioUrl: "",
  },
  {
    id: 19,
    title: "Shivers",
    artist: "Ed Sheeran",
    artistId: 9,
    album: "=",
    releaseYear: 2021,
    duration: 207,
    genre: "Pop",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+shivers+ed+sheeran",
    audioUrl: "",
  },
  {
    id: 20,
    title: "Woman",
    artist: "Doja Cat",
    artistId: 8,
    album: "Planet Her",
    releaseYear: 2021,
    duration: 172,
    genre: "R&B",
    coverArt: "/placeholder.svg?height=300&width=300&query=album+cover+woman+doja+cat",
    audioUrl: "",
  },
]

export const mockPlaylists = [
  {
    id: 1,
    title: "Today's Top Hits",
    description: "The most popular songs right now",
    creator: "Melody",
    type: "playlist",
    songIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+todays+top+hits",
  },
  {
    id: 2,
    title: "Chill Vibes",
    description: "Relaxing tunes to unwind",
    creator: "Melody",
    type: "playlist",
    songIds: [11, 12, 13, 14, 15],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+chill+vibes",
  },
  {
    id: 3,
    title: "Workout Motivation",
    description: "Energy-boosting tracks for your workout",
    creator: "Melody",
    type: "playlist",
    songIds: [3, 5, 7, 9, 16],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+workout+motivation",
  },
  {
    id: 4,
    title: "Pop Essentials",
    description: "The best pop songs of all time",
    creator: "Melody",
    type: "playlist",
    songIds: [1, 3, 4, 6, 8, 11, 13, 17, 19],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+pop+essentials",
  },
  {
    id: 5,
    title: "R&B Mix",
    description: "Smooth R&B tracks for your soul",
    creator: "Melody",
    type: "playlist",
    songIds: [10, 12, 14, 20],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+rnb+mix",
  },
  {
    id: 6,
    title: "Indie Discoveries",
    description: "Fresh indie tracks you need to hear",
    creator: "Melody",
    type: "playlist",
    songIds: [18, 15, 7],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+indie+discoveries",
  },
  {
    id: 7,
    title: "2021 Hits",
    description: "The biggest songs of 2021",
    creator: "Melody",
    type: "playlist",
    songIds: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+2021+hits",
  },
  {
    id: 8,
    title: "Dance Party",
    description: "Get the party started with these dance hits",
    creator: "Melody",
    type: "playlist",
    songIds: [3, 5, 8, 13, 16, 20],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+dance+party",
  },
  {
    id: 9,
    title: "Mood Booster",
    description: "Feel-good songs to lift your spirits",
    creator: "Melody",
    type: "playlist",
    songIds: [4, 5, 8, 13, 14, 18],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+mood+booster",
  },
  {
    id: 10,
    title: "Acoustic Covers",
    description: "Stripped-down versions of popular songs",
    creator: "Melody",
    type: "playlist",
    songIds: [2, 6, 11, 17, 19],
    coverArt: "/placeholder.svg?height=300&width=300&query=playlist+cover+acoustic+covers",
  },
]

export const mockArtists = [
  {
    id: 1,
    name: "The Weeknd",
    genre: "R&B/Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+the+weeknd",
  },
  {
    id: 2,
    name: "Dua Lipa",
    genre: "Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+dua+lipa",
  },
  {
    id: 3,
    name: "Harry Styles",
    genre: "Pop Rock",
    image: "/placeholder.svg?height=300&width=300&query=artist+harry+styles",
  },
  {
    id: 4,
    name: "BTS",
    genre: "K-pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+bts",
  },
  {
    id: 5,
    name: "Olivia Rodrigo",
    genre: "Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+olivia+rodrigo",
  },
  {
    id: 6,
    name: "The Kid LAROI",
    genre: "Pop/Hip-Hop",
    image: "/placeholder.svg?height=300&width=300&query=artist+the+kid+laroi",
  },
  {
    id: 7,
    name: "Lil Nas X",
    genre: "Hip-Hop/Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+lil+nas+x",
  },
  {
    id: 8,
    name: "Doja Cat",
    genre: "R&B/Hip-Hop",
    image: "/placeholder.svg?height=300&width=300&query=artist+doja+cat",
  },
  {
    id: 9,
    name: "Ed Sheeran",
    genre: "Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+ed+sheeran",
  },
  {
    id: 10,
    name: "Justin Bieber",
    genre: "Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+justin+bieber",
  },
  {
    id: 11,
    name: "Silk Sonic",
    genre: "R&B/Soul",
    image: "/placeholder.svg?height=300&width=300&query=artist+silk+sonic",
  },
  {
    id: 12,
    name: "Billie Eilish",
    genre: "Alternative/Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+billie+eilish",
  },
  {
    id: 13,
    name: "Adele",
    genre: "Pop/Soul",
    image: "/placeholder.svg?height=300&width=300&query=artist+adele",
  },
  {
    id: 14,
    name: "Glass Animals",
    genre: "Indie Pop",
    image: "/placeholder.svg?height=300&width=300&query=artist+glass+animals",
  },
]
